// <auto-generated />
namespace ContentProject.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class display_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(display_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202112281243206_display_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
