// <auto-generated />
namespace ContentProject.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_content_addisActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_content_addisActive));
        
        string IMigrationMetadata.Id
        {
            get { return "202112131413456_mig_content_addisActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
